name: bw-workers
env_file:
  - .env
services:
  cli:
    type: php:7.3
    build:
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
tooling:
  php:
    service: cli
    cmd: php
  composer:
    service: cli
    cmd: composer
  phpcs:
    service: cli
    cmd:
      - "/app/vendor/bin/phpcs -n --report=full --standard=/app/vendor/backdrop/coder/coder_sniffer/Backdrop --ignore=vendor/*,README.md --extensions=install,module,php,inc,theme"
